PUT /_ingest/pipeline/dms-backend-pipeline
{
  "description": "Custom ingest pipeline for parsing the log",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log_level} \\[Process:%{INT:process_id}/Thread:%{INT:thread_id}] %{DATA:logger}:\\d+ - %{QS:request_method} %{INT:http_status_code} %{INT:response_size}",
          "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:log_level} \\[Process:%{NUMBER:process}/Thread:%{NUMBER:thread}\\] %{DATA:logger}\\:%{NUMBER:line} - %{GREEDYDATA:message}"
        ]
      }
    },
    {
      "date": {
        "field": "timestamp",
        "target_field": "@timestamp",
        "formats": ["yyyy-MM-dd HH:mm:ss"]
      }
    },
    {
      "convert": {
        "field": "process",
        "type": "integer"
      }
    },
    {
      "convert": {
        "field": "thread",
        "type": "double"
      }
    },
    {
      "convert": {
        "field": "http_status_code",
        "type": "integer",
        "ignore_missing": true
      }
    },
    {
      "convert": {
        "field": "response_size",
        "type": "double",
        "ignore_missing": true
      }
    }
  ]
}
